services:
  app:
    restart: always
    network_mode: 'host'
    build: .
    volumes:
      - ./log:/var/log/apache2
      - ./letsencrypt:/etc/letsencrypt
      - ./sites-enabled:/etc/apache2/sites-enabled
      - ./conf-available/other-vhosts-access-log.conf:/etc/apache2/conf-available/other-vhosts-access-log.conf
      - ./html:/var/www/html
